name: Build Post Index

on:
  push:
    paths:
      - 'posts/**/*.md'
      - '.github/workflows/update_posts.yml'
      - 'tags.json'
      - 'update_posts.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate posts.json
        run: python3 update_posts.py

      - name: Commit posts.json
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posts.json
          git commit -m "Update posts index" || echo "No changes to commit"
          git push
